###
# connectivity-checker
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: application
    component: connectivity-checker
  name: connectivity-checker
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: application
      component: connectivity-checker
  template:
    metadata:
      labels:
        cluster: application
        component: connectivity-checker
    spec:
      containers:
      - name: connectivity-checker
        image: __NPH_REGISTRY/__NPH_REGISTRY_NAMESPACE/connectivity-checker:__NPH_VERSION
        imagePullPolicy: Always
        args:
          - "run"
          - "--debug"
          - "--port=8384"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
